Repository Potenday14/moodeat-backend, pull requests merged in 2024-12, with the labels that each got.

#5 feat: entity class
  src/main/java/com/moodeat/controller/ExampleRecipeController.java
  src/main/java/com/moodeat/domain/Character.java
  src/main/java/com/moodeat/domain/Ingredient.java
  src/main/java/com/moodeat/domain/ManualStep.java
  src/main/java/com/moodeat/domain/Message.java
  src/main/java/com/moodeat/domain/Recipe.java
  src/main/java/com/moodeat/domain/RecipeIngredient.java
  src/main/java/com/moodeat/domain/RecipeRecommendation.java
  src/main/java/com/moodeat/domain/User.java
  src/main/java/com/moodeat/domain/UserRecipeRecommendation.java
  src/main/java/com/moodeat/domain/enums/IngredientType.java
  src/main/java/com/moodeat/domain/enums/MessageRole.java
  src/main/java/com/moodeat/domain/enums/Mood.java
  src/main/java/com/moodeat/dto/ExampleErrorResponse.java
  src/main/java/com/moodeat/dto/recipe/ExampleRequestCreateRecipe.java
  src/main/java/com/moodeat/dto/recipe/ExampleResponseCreateRecipe.java
Labels: Backend, DB

#14 Feature#3 java version up
  README.md
  build.gradle
Labels: Backend

#16 build : docker java 21 로 변경
  DeployDockerfile
  Dockerfile
Labels: Backend, environment

#22 Feature#19 mockup data
  .github/workflows/hotDeploy.yml
  src/main/java/com/moodeat/controller/CharacterController.java
  src/main/java/com/moodeat/controller/IngredientController.java
  src/main/java/com/moodeat/controller/RecipeController.java
  src/main/java/com/moodeat/controller/RecipeRecommendationController.java
  src/main/java/com/moodeat/domain/Recipe.java
  src/main/java/com/moodeat/domain/UserRecipeRecommendation.java
  src/main/java/com/moodeat/dto/mockup/MockupResponseGetCharacters.java
  src/main/java/com/moodeat/dto/mockup/MockupResponseGetIngredients.java
  src/main/java/com/moodeat/dto/mockup/MockupResponseGetRecipeRecommendationsById.java
  src/main/java/com/moodeat/dto/mockup/MockupResponseGetRecipesById.java
  src/main/java/com/moodeat/dto/mockup/MockupResponsePostRecipeRecommendations.java
  src/main/java/com/moodeat/repository/recipe/RecipeQueryDsl.java
  src/main/java/com/moodeat/repository/recipe/RecipeQueryDslImpl.java
  src/main/java/com/moodeat/repository/recipe/RecipeRepository.java
  src/main/java/com/moodeat/service/RecipeRecommendationService.java
  src/main/java/com/moodeat/service/RecipeService.java
Labels: Backend, API

#23 API 목업데이터 반환
  .github/workflows/hotDeploy.yml
  src/main/java/com/moodeat/controller/CharacterController.java
  src/main/java/com/moodeat/controller/IngredientController.java
  src/main/java/com/moodeat/controller/RecipeController.java
  src/main/java/com/moodeat/controller/RecipeRecommendationController.java
  src/main/java/com/moodeat/domain/Recipe.java
  src/main/java/com/moodeat/domain/UserRecipeRecommendation.java
  src/main/java/com/moodeat/dto/mockup/MockupResponseGetCharacters.java
  src/main/java/com/moodeat/dto/mockup/MockupResponseGetIngredients.java
  src/main/java/com/moodeat/dto/mockup/MockupResponseGetRecipeRecommendationsById.java
  src/main/java/com/moodeat/dto/mockup/MockupResponseGetRecipesById.java
  src/main/java/com/moodeat/dto/mockup/MockupResponsePostRecipeRecommendations.java
  src/main/java/com/moodeat/repository/recipe/RecipeQueryDsl.java
  src/main/java/com/moodeat/repository/recipe/RecipeQueryDslImpl.java
  src/main/java/com/moodeat/repository/recipe/RecipeRepository.java
  src/main/java/com/moodeat/service/RecipeRecommendationService.java
  src/main/java/com/moodeat/service/RecipeService.java
Labels: Backend, API

#24 feat : 목업 데이터 수정
  src/main/java/com/moodeat/dto/mockup/MockupResponseGetRecipesById.java
  src/main/java/com/moodeat/dto/recipe/RecipeDto.java
  src/main/java/com/moodeat/dto/recipe/recommendation/ResponseGetRecipeRecommendationsById.java
Labels: Backend, API

#25 feat : 서비스, 리포지토리 단 구성 완료
  src/main/java/com/moodeat/controller/CharacterController.java
  src/main/java/com/moodeat/controller/IngredientController.java
  src/main/java/com/moodeat/controller/RecipeController.java
  src/main/java/com/moodeat/controller/RecipeRecommendationController.java
  src/main/java/com/moodeat/repository/character/CharacterRepository.java
  src/main/java/com/moodeat/repository/ingredient/IngredientRepository.java
  src/main/java/com/moodeat/repository/recipe/ingredient/RecipeIngredientRepository.java
  src/main/java/com/moodeat/repository/recipe/recommendation/RecipeRecommendationRepository.java
  src/main/java/com/moodeat/repository/user/UserRepository.java
  src/main/java/com/moodeat/repository/user/recipe/recommendation/UserRecipeRecommendationRepository.java
  src/main/java/com/moodeat/service/CharacterService.java
  src/main/java/com/moodeat/service/IngredientService.java
  src/main/java/com/moodeat/service/RecipeRecommendationService.java
Labels: Backend, environment

#27 feat: openAPI 응답 및 데이터베이스 데이터 파일 추가
  src/main/java/com/moodeat/constant/ingredient_data.csv
  src/main/java/com/moodeat/constant/open-api-recipe-response.json
  src/main/java/com/moodeat/constant/recipe_data.csv
  src/main/java/com/moodeat/constant/recipe_ingredient_data.csv
Labels: Backend, DB

#28 Feature#20 openapi data
  src/main/java/com/moodeat/constant/recipe_data.csv
  src/main/java/com/moodeat/domain/Recipe.java
Labels: Backend, DB

#29 2차 배포
  .gitignore
  src/main/java/com/moodeat/constant/ingredient_data.csv
  src/main/java/com/moodeat/constant/open-api-recipe-response.json
  src/main/java/com/moodeat/constant/recipe_data.csv
  src/main/java/com/moodeat/constant/recipe_ingredient_data.csv
  src/main/java/com/moodeat/controller/CharacterController.java
  src/main/java/com/moodeat/controller/IngredientController.java
  src/main/java/com/moodeat/controller/RecipeController.java
  src/main/java/com/moodeat/controller/RecipeRecommendationController.java
  src/main/java/com/moodeat/domain/Recipe.java
  src/main/java/com/moodeat/domain/RecipeIngredient.java
  src/main/java/com/moodeat/dto/mockup/MockupResponseGetRecipesById.java
  src/main/java/com/moodeat/dto/recipe/RecipeDto.java
  src/main/java/com/moodeat/dto/recipe/recommendation/ResponseGetRecipeRecommendationsById.java
  src/main/java/com/moodeat/repository/character/CharacterRepository.java
  src/main/java/com/moodeat/repository/ingredient/IngredientRepository.java
  src/main/java/com/moodeat/repository/recipe/ingredient/RecipeIngredientRepository.java
  src/main/java/com/moodeat/repository/recipe/recommendation/RecipeRecommendationRepository.java
  src/main/java/com/moodeat/repository/user/UserRepository.java
  src/main/java/com/moodeat/repository/user/recipe/recommendation/UserRecipeRecommendationRepository.java
  src/main/java/com/moodeat/service/CharacterService.java
  src/main/java/com/moodeat/service/IngredientService.java
  src/main/java/com/moodeat/service/RecipeRecommendationService.java
Labels: Backend

#38 feat: 캐릭터 닉네임 필드 추가
  src/main/java/com/moodeat/domain/Character.java
  src/main/java/com/moodeat/domain/enums/Nickname.java
Labels: Backend, DB

#43 Feature#9 ingredients advance
  src/main/java/com/moodeat/repository/ingredient/IngredientRepository.java
  src/main/java/com/moodeat/service/IngredientService.java
Labels: Backend, API

#44 Feature#10 create recommendation
  src/main/java/com/moodeat/controller/RecipeRecommendationController.java
  src/main/java/com/moodeat/domain/Message.java
  src/main/java/com/moodeat/domain/UserRecipeRecommendation.java
  src/main/java/com/moodeat/repository/recipe/RecipeRepository.java
  src/main/java/com/moodeat/service/CharacterService.java
  src/main/java/com/moodeat/service/ClovaService.java
  src/main/java/com/moodeat/service/RecipeRecommendationService.java
  src/main/java/com/moodeat/service/RecipeService.java
Labels: Backend, API

#46 Feature#11 get recommendation
  .gitignore
  src/main/java/com/moodeat/controller/RecipeRecommendationController.java
  src/main/java/com/moodeat/dto/mockup/MockupResponseGetRecipeRecommendationsById.java
  src/main/java/com/moodeat/dto/recipe/recommendation/RecipeRecommendationRecipeDto.java
  src/main/java/com/moodeat/dto/recipe/recommendation/ResponseGetRecipeRecommendationsById.java
  src/main/java/com/moodeat/service/ClovaService.java
  src/main/java/com/moodeat/service/RecipeRecommendationService.java
  src/main/java/com/moodeat/service/RecipeService.java
Labels: Backend, API

#52 Feature#51 clova 성능 개선
  src/main/java/com/moodeat/domain/UserRecipeRecommendation.java
  src/main/java/com/moodeat/service/ClovaService.java
Labels: Backend, API

#55 fix: 클로바 응답 형식 json 강제
  src/main/java/com/moodeat/service/ClovaService.java
Labels: Backend, API

#59 Feature#57 refactoring
  build.gradle
  src/main/java/com/moodeat/controller/RecipeRecommendationController.java
  src/main/java/com/moodeat/dto/clova/ChatCompletionsDto.java
  src/main/java/com/moodeat/dto/clova/RequestCreateRecipeRecommendation.java
  src/main/java/com/moodeat/dto/clova/ResponseCreateRecipeRecommendation.java
  src/main/java/com/moodeat/dto/recipe/recommendation/RecipeRecommendationRecipeDto.java
  src/main/java/com/moodeat/dto/recipe/recommendation/RequestPostRecipeRecommendations.java
  src/main/java/com/moodeat/dto/recipe/recommendation/ResponseGetRecipeRecommendationsById.java
  src/main/java/com/moodeat/repository/recipe/RecipeRepository.java
  src/main/java/com/moodeat/service/CharacterService.java
  src/main/java/com/moodeat/service/ClovaService.java
  src/main/java/com/moodeat/service/RecipeRecommendationService.java
  src/main/java/com/moodeat/service/RecipeService.java
Labels: enhancement, Backend

#60 1차 리팩토링
  build.gradle
  src/main/java/com/moodeat/controller/RecipeRecommendationController.java
  src/main/java/com/moodeat/dto/clova/ChatCompletionsDto.java
  src/main/java/com/moodeat/dto/clova/RequestCreateRecipeRecommendation.java
  src/main/java/com/moodeat/dto/clova/ResponseCreateRecipeRecommendation.java
  src/main/java/com/moodeat/dto/recipe/recommendation/RecipeRecommendationRecipeDto.java
  src/main/java/com/moodeat/dto/recipe/recommendation/RequestPostRecipeRecommendations.java
  src/main/java/com/moodeat/dto/recipe/recommendation/ResponseGetRecipeRecommendationsById.java
  src/main/java/com/moodeat/repository/recipe/RecipeRepository.java
  src/main/java/com/moodeat/service/CharacterService.java
  src/main/java/com/moodeat/service/ClovaService.java
  src/main/java/com/moodeat/service/RecipeRecommendationService.java
  src/main/java/com/moodeat/service/RecipeService.java
Labels: enhancement, Backend
